# Generated by Django 4.0.10 on 2024-08-10 06:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caretip_plant_care_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.plant_image_file_path),
        ),
    ]
